BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `TTRANSACTIONS` (
	`TXHASH`	TEXT,
	`ADDRESS`	TEXT,
	`DATA_HASH`	TEXT,
	`CHUNK_IDX`	INTEGER,
	`CHUNK_SIZE`	INTEGER,
	`CHUNK_HASH`	TEXT,
	`NETWORK`	TEXT,
	PRIMARY KEY(`TXHASH`)
);
CREATE TABLE IF NOT EXISTS `TSTOREDDATA` (
	`HASH`	TEXT,
	`NAME`	TEXT,
	`SIZE`	INTEGER,
	`NETWORK`	TEXT,
	PRIMARY KEY(`HASH`)
);
CREATE TABLE IF NOT EXISTS `TBANDWIDTH_REMAINING` (
	`BANDWIDTH`	INTEGER,
	`NETWORK`	TEXT,
	PRIMARY KEY(`NETWORK`)
);
CREATE TABLE IF NOT EXISTS `TACCOUNTS` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`ADDRESS`	TEXT UNIQUE,
	`PRIVKEY`	TEXT,
	`PUBKEY`	TEXT,
	`ADDRESS_HEX`	TEXT,
	`INITIALISED`	INTEGER DEFAULT 0,
	`NETWORK`	TEXT,
	`BANDWIDTH_REMAINING`	INTEGER DEFAULT 0
);
CREATE TABLE IF NOT EXISTS `TACCOUNTINIT` (
	`TXHASH`	TEXT,
	`ADDRESS`	TEXT,
	`NETWORK`	TEXT,
	PRIMARY KEY(`TXHASH`)
);
COMMIT;
